# Write your MySQL query statement below
SELECT P.PRODUCT_ID, P.PRODUCT_NAME FROM PRODUCT P
JOIN SALES S USING (PRODUCT_ID)
GROUP BY PRODUCT_ID
HAVING MIN(S.SALE_DATE) >= '2019-01-01'  AND MAX(S.SALE_DATE) <= '2019-03-31';